---
# tasks file for scout - EL Family

- name: EL Family | Downloading and setting up {{ scout_app }} {{ scout_version }}
  get_url:
    url: "{{ scout_dl_url }}"
    dest: "{{ scout_bin_path }}"
    mode: "{{ scout_bin_permission_mode }}"
